spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

jwt.token-validity-in-seconds: 1800
jwt.refresh-token-validity-in-seconds: 1209600

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
  serverAddress: 52.78.115.221

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
  serverAddress: 52.78.115.221

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto:
    show-sql: true

---
security:
  debug: true

logging:
  level:
    org.springframework.security.web: TRACE
    org.springframework.security.authentication: TRACE